### PR TITLE
Dict logic

### PR DESCRIPTION
**Pull request by TrentHawkins**
This is a new implementation to encapsulate square operations for easily coding any move operations without the need to re-implement component-wise additions. Also, (per @palasso's recommendation in a live session), with annotated square indices (`rank` and `file` respectively) we do away with any bugs due to misused order of indices.

### CODE REVIEW

**Comment by prototact** [comment]
Subclassing base python classes is not recommended. It reduces readability and inherits methods that do not necessarily make sense. By defining the inner python class as an attribute, we expose only the functionality that is necessary to the user. Also, I do not see the reason why we need to subclass `Square` from `Indices` instead of directly defining `Square`. It is best to avoid inheritance and introduce classes as little as possible. Finally, using dicts is overkill, just use a tuple and properties decorator.

```python
File = int
Rank = int
Indices = tuple[Rank, File]

class Square:
    # Valid values for chess notation:
    rank_range = "87654321"  # This is upside down because rows in a nested list expand downwards but ranks in chess go upwards.
    file_range = "abcdefgh"

    # Matching between rank and file in chess notation and simple (top-down) array indexing:
    index_to_file = {index_: file_ for index_, file_ in zip(range(8), file_range)}  # translate range index to file in chess
    file_to_index = {file_: index_ for index_, file_ in zip(range(8), file_range)}  # translate file in chess to range index
    index_to_rank = {index_: rank_ for index_, rank_ in zip(range(8), rank_range)}  # translate range index to rank in chess
    rank_to_index = {rank_: index_ for index_, rank_ in zip(range(8), rank_range)}  # translate rank in chess to range index
    # Useful for asserting string input of notation is correct:
    notation_range = re.compile(f"[{file_range}][{rank_range}]")

    def __init__(self, square: Indices | str) -> None:
        """Make a square out of chess notation.
        Args:
            square: The rank and file in either chess notation or rank and file indices.
        """
        # If given in notation translate it to indices to make the square.
        if isinstance(square, str):
            assert self.notation_range.match(square)
            self._square = (self.rank_to_index[square[1]], self.file_to_index[square[0]])
        # Otherwise, if given alreay as an `Indices` object, simply dict expand it to make the square (basically making a copy).
        else:
            self._square = square

    @property
    def rank(self) -> Rank:
        return self._square[0]

    @property
    def file(self) -> File:
        return self._square[1]

    def __sub__(self, other: Square) -> Square:
        return Square((self.rank - other.rank, self.file - other.file))

    def __add__(self, other: Square) -> Square:
        return Square((self.rank + other.rank, self.file + other.file))

    def __mul__(self, times:int) -> Square:
        return Square((self.rank * times, self.file * times))

    def __repr__(self) -> str:
        """Represent square in chess notaion.
        Returns:
            The rank and file of square in chess notation.
        """
        return self.index_to_file[self.file] + self.index_to_rank[self.rank]
```

**Comment by TrentHawkins** [comment]
I like this. The reason there are two classes to begin with (regardless of inheritance) is to differentiate between what is a square and what is a diff of squares. However, if squares are made immutable like in your implementation, and possibility of initialization include both annotation and coordinate setting, they may be merged into one class, even though distinctly squares and square diffs are different semantically. I will eliminate the unnecessary inheritance from `dict` and implement it with properties like you did. What is your take on the two classes—one for squares and one for diffs—versus one square class for all?

**Comment by prototact** [comment]
I see the problem now and I believe having classes for Squares and Moves is confusing. I think it' s better to return to previous form. It's important to not define things without a reason, and specifically think backwards from the user input and chess logic.

- Chess notation and translation to `Rank` and `File` should be hidden within the Board class
- there should be functions only for the difference between Squares (`tuple[int, int]`) and Moves (`tuple[int, int]`) and advancement of Square by Move
    ```python
    Rank = int
    File = int
    Square = tuple[int, int]
    Move = tuple[int, int]

    def rank(square:Square) -> Rank:
        return square[0]
    
    def file(square:Square) -> File:
        return square[1]

    def horizontal(move:Move) -> int:
        return move[0]

    def vertical(move:Move) -> int:
        return move[1]

    def difference(square_left: Square, square_right:Square) -> Move:
        horizontal_ = rank(square_right) - rank(square_left)
        vertical_ = file(square_right) - file(square_left)
        return horizontal_, vertical_       

   def advancement(square:Square, move:Move) -> Square:
        rank_ = rank(square) + horizontal(move)
        file_ = file(square) + vertical(move)
        return rank_, file_   
    
    def decrement(move:Move, unit_move:Move) -> Move:
        horizontal_ = horizontal(move) - horizontal(unit_move)
        vertical_ = vertical(move) - vertical(unit_move)
        return horizontal_, vertical_
    ```
The real issue is how to check that a move is blocked by another piece or not.

```python
def check_move_blocked(self, square:Square, move:Move) -> bool:
    piece = self._board[rank(square)][file(square)]
    # a knight is a special case, it immediatly moves to the goto-square and is only blocked by 
    # piece of the same color.
    if isinstance(piece, Knight):
       square = advancement(square, move)
       other_piece = self._board[rank(square)][file(square)]
       return other_piece is not None and other_piece.is_black == piece.is_black
    blocked = False
    while not blocked:
        # a pawn moving diagonally is a special case, currently not addressed here.
        # we can do this in a previous call (checks whether the move is a valid move for the piece independent of blocking)
        unit_move = piece.unit_move(move)
        move = decrement(move, unit_move)
        # if move reaches goto_square and the color of any chest piece there is different, the chess piece is not blocked
        if move == (0, 0):
            other_piece = self._board[rank(square)][file(square)]
            return other_piece is not None and other_piece.is_black == piece.is_black
        square = advancement(square, unit_move)
        # even if there is another piece of the opposite color on the square, we decide it blocks movement.
        # another way to handle this is to automatically move the piece up to that square instead of the go-to one.
        # in that case we should return the position the piece moves to, in order to update the board properly.
        blocked = self._board[rank(square)][file(square)] is not None

    return blocked
```

**Comment by TrentHawkins** [comment]
I am adapting parts of your code to an object-oriented logic involving a `Vector` diff type and a `Square` type as I aforementioned. I still purse an OO approach in this branch, but maybe you are onto something, can you branch out from an appropriate point and commit your proposed changes (if you have time). I find the dict logic a dead end, but I leave this branch and pull request open just in case. I am now working on a basic rank-and-file `dataclass` that Squares use and inherit from, inspired from your code snippet.

**Pull request closed without merging**
